-- Administrator setup: dedicated synthetic-demo database only. No credentials belong here.
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS REVENUE_METRICS_DEMO;
CREATE WAREHOUSE IF NOT EXISTS RMP_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE SCHEMA IF NOT EXISTS REVENUE_METRICS_DEMO.RAW;
CREATE SCHEMA IF NOT EXISTS REVENUE_METRICS_DEMO.CONSUMER;
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS RMP_LOADER;
CREATE ROLE IF NOT EXISTS RMP_BUILD;
CREATE ROLE IF NOT EXISTS RMP_CONSUMER;
GRANT ROLE RMP_LOADER TO ROLE SYSADMIN;
GRANT ROLE RMP_BUILD TO ROLE SYSADMIN;
GRANT ROLE RMP_CONSUMER TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE RMP_WH TO ROLE RMP_LOADER;
GRANT USAGE ON WAREHOUSE RMP_WH TO ROLE RMP_BUILD;
GRANT USAGE ON WAREHOUSE RMP_WH TO ROLE RMP_CONSUMER;
GRANT USAGE ON DATABASE REVENUE_METRICS_DEMO TO ROLE RMP_LOADER;
GRANT USAGE ON DATABASE REVENUE_METRICS_DEMO TO ROLE RMP_BUILD;
GRANT USAGE ON DATABASE REVENUE_METRICS_DEMO TO ROLE RMP_CONSUMER;
GRANT USAGE, CREATE TABLE ON SCHEMA REVENUE_METRICS_DEMO.RAW TO ROLE RMP_LOADER;
GRANT USAGE ON SCHEMA REVENUE_METRICS_DEMO.RAW TO ROLE RMP_BUILD;
GRANT SELECT ON ALL TABLES IN SCHEMA REVENUE_METRICS_DEMO.RAW TO ROLE RMP_BUILD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REVENUE_METRICS_DEMO.RAW TO ROLE RMP_BUILD;
GRANT CREATE SCHEMA ON DATABASE REVENUE_METRICS_DEMO TO ROLE RMP_BUILD;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA REVENUE_METRICS_DEMO.CONSUMER TO ROLE RMP_BUILD;
GRANT USAGE ON SCHEMA REVENUE_METRICS_DEMO.CONSUMER TO ROLE RMP_CONSUMER;
-- Assign each role to an appropriate user with registered key-pair authentication.
-- Example placeholders (replace; do not commit usernames or keys):
-- GRANT ROLE RMP_LOADER TO USER <loader_user>;
-- GRANT ROLE RMP_BUILD TO USER <build_user>;
-- GRANT ROLE RMP_CONSUMER TO USER <consumer_user>;
-- The demo verifier uses one existing user with these three roles, always with
-- secondary roles disabled. Production identities should be separately provisioned.
